# Generated by Django 4.1.1 on 2022-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_course',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
