# Generated by Django 4.1.1 on 2022-11-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0002_user_course_title_alter_user_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='videoz',
        ),
    ]
