# Generated by Django 4.1.1 on 2023-04-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0002_add_subject_document_duration_trainers_user_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='course_week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interapp.duration'),
        ),
        migrations.AddField(
            model_name='video',
            name='course_week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interapp.duration'),
        ),
    ]
