# Generated by Django 4.1.1 on 2022-11-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0003_remove_user_course_videoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_course',
            name='assignment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user_course',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.trainers'),
        ),
        migrations.AlterField(
            model_name='user_course',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
