# Generated by Django 4.1.1 on 2022-11-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0004_alter_user_course_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_course',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
