# Generated by Django 4.1.1 on 2023-04-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0005_alter_quizresult_course_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='course_week',
        ),
    ]
