# Generated by Django 4.1.1 on 2022-11-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0005_alter_user_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
