# Generated by Django 4.1.1 on 2022-11-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0006_user_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
