# Generated by Django 4.1.1 on 2023-04-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0006_remove_quizresult_course_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='course_week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interapp.duration'),
        ),
    ]
