# Generated by Django 4.1.1 on 2022-11-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0007_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='Certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_course',
            name='Skillevel',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
