# Generated by Django 4.1.1 on 2022-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0008_user_course_certificate_user_course_skillevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_course',
            name='Certificate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=200, null=True),
        ),
    ]
