# Generated by Django 4.1.1 on 2023-02-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0009_alter_user_course_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myfile',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
