# Generated by Django 4.1.1 on 2023-04-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0009_alter_quizresult_course_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trainers',
        ),
        migrations.AddField(
            model_name='quizdetail',
            name='course_week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interapp.duration'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='weeks',
            field=models.IntegerField(unique=True),
        ),
    ]
