# Generated by Django 4.1.1 on 2023-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0010_user_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('is_company', 'is_company'), ('is_student', 'is_student'), ('is_admin', 'is_admin'), ('is_superadmin', 'is_superadmin'), ('None', 'None')], default='', max_length=100),
        ),
    ]
