# Generated by Django 4.1.1 on 2023-04-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0011_quizprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
        migrations.AddField(
            model_name='user_course',
            name='promo',
            field=models.FileField(default='', upload_to='video'),
        ),
    ]
