# Generated by Django 4.1.1 on 2023-02-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0011_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
