# Generated by Django 4.1.1 on 2023-04-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0012_remove_video_completed_remove_video_preview_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interapp.user_course'),
        ),
    ]
