# Generated by Django 4.1.1 on 2023-04-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0013_alter_quizprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.user_course'),
        ),
    ]
