# Generated by Django 4.1.1 on 2023-02-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0013_user_is_company_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('is_company', 'is_company'), ('is_student', 'is_student'), ('is_admin', 'is_admin'), ('None', 'None')], default='', max_length=100),
        ),
    ]
