# Generated by Django 4.1.1 on 2023-02-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0014_alter_user_is_active_alter_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_comp_approved',
            field=models.BooleanField(default=False),
        ),
    ]
