# Generated by Django 4.1.1 on 2023-02-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0015_user_is_comp_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
