# Generated by Django 4.1.1 on 2023-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0016_video_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.CharField(max_length=500),
        ),
    ]
