# Generated by Django 4.1.1 on 2023-02-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0017_alter_video_time_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_course',
            name='Skillevel',
        ),
        migrations.AlterField(
            model_name='user_course',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
