# Generated by Django 4.1.1 on 2023-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0018_resume_remove_user_course_skillevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='user_course',
            name='course_week',
            field=models.CharField(default='', max_length=20),
        ),
    ]
