# Generated by Django 4.1.1 on 2023-02-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0019_remove_user_course_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_subject',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField(default='')),
                ('desc', models.TextField(blank=True)),
                ('course_week', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='')),
                ('outcomes', models.TextField()),
                ('assignment', models.TextField(default='')),
                ('Certificate', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
