# Generated by Django 4.1.1 on 2023-03-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0024_quiztaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
