# Generated by Django 4.1.1 on 2023-03-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0026_resumme_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumme',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
