# Generated by Django 4.1.1 on 2023-03-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0027_alter_resumme_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.user_course')),
            ],
        ),
    ]
