# Generated by Django 4.1.1 on 2023-03-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0030_alter_orderplaced_product_alter_orderplaced_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='products',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interapp.add_subject'),
        ),
    ]
