# Generated by Django 4.1.1 on 2023-03-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0032_cart_products_alter_orderplaced_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='products',
        ),
    ]
