# Generated by Django 4.1.1 on 2023-03-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0033_remove_cart_products_remove_orderplaced_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='duration_minutes',
        ),
    ]
