# Generated by Django 4.1.1 on 2023-03-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0034_remove_quesmodel_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
