# Generated by Django 4.1.1 on 2023-03-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0035_user_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='description',
        ),
    ]
