# Generated by Django 4.1.1 on 2023-03-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0036_remove_user_course_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_purchase',
        ),
    ]
