# Generated by Django 4.1.1 on 2023-03-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0039_delete_course_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBackStudent',
        ),
    ]
