# Generated by Django 4.1.1 on 2023-03-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0041_feedbackstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackStudent',
            new_name='FeedBackStudents',
        ),
    ]
