# Generated by Django 4.1.1 on 2023-03-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0042_rename_feedbackstudent_feedbackstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBackStudents',
        ),
    ]
