# Generated by Django 4.1.1 on 2023-03-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0045_alter_document_title_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumme',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
