# Generated by Django 4.1.1 on 2023-03-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0046_alter_resumme_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumme',
            name='dob',
        ),
    ]
