# Generated by Django 4.1.1 on 2023-04-03 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0048_remove_quiztaker_quiz_remove_quiztaker_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=0, max_length=70)),
                ('score', models.CharField(default=0, max_length=10)),
                ('time', models.CharField(default=0, max_length=10)),
                ('correct', models.CharField(default=0, max_length=10)),
                ('wrong', models.CharField(default=0, max_length=10)),
                ('percent', models.CharField(default=0, max_length=10)),
                ('total', models.CharField(default=0, max_length=10, verbose_name='total questions')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.user_course')),
            ],
            options={
                'verbose_name_plural': 'Quiz - Result',
            },
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('date_finished', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.quesmodel')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.quizresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
