# Generated by Django 4.1.1 on 2023-04-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0049_quizresult_quiztaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizTaker',
        ),
    ]
